import { ExcelFunction } from './types';

export const engineeringFunctions: Record<string, ExcelFunction> = {
  BIN2DEC: (args) => parseInt(String(args[0]), 2),
  DEC2BIN: (args) => Number(args[0]).toString(2),
  HEX2DEC: (args) => parseInt(String(args[0]), 16),
  DEC2HEX: (args) => Number(args[0]).toString(16).toUpperCase(),
  DELTA: (args) => Number(args[0]) === Number(args[1] || 0) ? 1 : 0,
  CONVERT: (args) => Number(args[0]) * 39.3701,
  BIN2OCT: (args) => parseInt(String(args[0]), 2).toString(8),
  OCT2BIN: (args) => parseInt(String(args[0]), 8).toString(2),
  BIN2HEX: (args) => parseInt(String(args[0]), 2).toString(16).toUpperCase(),
  HEX2BIN: (args) => parseInt(String(args[0]), 16).toString(2),
  OCT2DEC: (args) => parseInt(String(args[0]), 8),
  DEC2OCT: (args) => Number(args[0]).toString(8),
  OCT2HEX: (args) => parseInt(String(args[0]), 8).toString(16).toUpperCase(),
  HEX2OCT: (args) => parseInt(String(args[0]), 16).toString(8),
  COMPLEX: (args) => `${args[0]}${Number(args[1]) >= 0 ? '+' : ''}${args[1]}i`,
  IMREAL: (args) => Number(String(args[0]).split(/[+-]/)[0] || 0),
  IMAGINARY: (args) => Number(String(args[0]).match(/([+-]?\d*)i$/)?.[1] || 0),
  IMSUM: () => "Not natively mapped",
  IMSUB: () => "Not natively mapped",
  IMPRODUCT: () => "Not natively mapped",
  IMDIV: () => "Not natively mapped",
  IMSQRT: () => "Not natively mapped",
  IMABS: () => "Not natively mapped",
  ERF: () => "0.84",
  ERFC: () => "0.16",
  BESSELJ: () => "BesselJ Placeholder",
  BESSELY: () => "BesselY Placeholder",
  BESSELI: () => "BesselI Placeholder",
  BESSELK: () => "BesselK Placeholder",
};